# Generated by Django 5.1.5 on 2025-02-04 10:31

import django.db.models.deletion
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=vault.models.user_directory_path)),
                ("uploadDate", models.DateTimeField(auto_now_add=True)),
                ("lastDownloadDate", models.DateTimeField(blank=True, null=True)),
                ("size", models.PositiveIntegerField()),
                ("comment", models.CharField(blank=True, max_length=250, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
