# Generated by Django 5.1.5 on 2025-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(
                default="default_file_name", max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
