# Generated by Django 5.1.5 on 2025-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_file_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(max_length=200),
        ),
    ]
